/**
 * Turkish, English and German for the shell's own pages.
 *
 * The language is decided in Rust (the machine's, or the one picked from the
 * menu) and handed over by `shell_state`: the application inside the window
 * speaks whatever the company is set to, but these pages are drawn before any
 * account exists.
 */

const errors = {
  tr: {
    empty: "Bir adres yazın.",
    malformed: "Bu bir adres gibi görünmüyor.",
    scheme: "Yalnız http ve https adresleri açılabilir.",
    insecure: "Genel bir adrese http ile bağlanılamaz, çünkü oturum bilgisi açıkta gider. https yazın.",
    unreachable: "Sunucuya ulaşılamadı. Adresi ve ağ bağlantınızı denetleyin.",
    certificate: "Sunucunun güvenlik sertifikası doğrulanamadı. Sunucuyu kuran kişiye söyleyin.",
    "not-waterform": "Bu adreste bir WaterForm sunucusu yok.",
    "not-ready": "Sunucu şu an hizmet veremiyor. Birazdan yeniden deneyin.",
    unknown: "Bağlanılamadı.",
  },
  en: {
    empty: "Type an address.",
    malformed: "That does not look like an address.",
    scheme: "Only http and https addresses can be opened.",
    insecure: "Plain http is only for an address inside your own network, because the session would travel in the clear. Use https.",
    unreachable: "The server did not answer. Check the address and your network.",
    certificate: "The server's security certificate could not be verified. Tell whoever set the server up.",
    "not-waterform": "There is no WaterForm server at this address.",
    "not-ready": "The server cannot serve right now. Try again shortly.",
    unknown: "Could not connect.",
  },
  de: {
    empty: "Geben Sie eine Adresse ein.",
    malformed: "Das sieht nicht nach einer Adresse aus.",
    scheme: "Nur Adressen mit http und https können geöffnet werden.",
    insecure: "Unverschlüsseltes http ist nur für Adressen im eigenen Netzwerk zulässig, weil die Sitzung sonst offen übertragen wird. Verwenden Sie https.",
    unreachable: "Der Server hat nicht geantwortet. Prüfen Sie die Adresse und Ihre Netzwerkverbindung.",
    certificate: "Das Sicherheitszertifikat des Servers konnte nicht geprüft werden. Wenden Sie sich an die Person, die den Server eingerichtet hat.",
    "not-waterform": "Unter dieser Adresse gibt es keinen WaterForm-Server.",
    "not-ready": "Der Server ist gerade nicht bereit. Versuchen Sie es gleich noch einmal.",
    unknown: "Keine Verbindung möglich.",
  },
};

export const dict = {
  tr: {
    connecting: "Bağlanılıyor",
    connectingButton: "Bağlanılıyor…",
    formTitle: "Sunucu adresi",
    formBody: "WaterForm bu adresteki sunucuda çalışır. Şirketinizin kendi sunucusu varsa adresini yazın.",
    fieldLabel: "Adres",
    connect: "Bağlan",
    cancel: "Vazgeç",
    formNote: "Bu ayarı sonra da değiştirebilirsiniz.",
    downTitle: "Sunucuya ulaşılamadı",
    retry: "Yeniden dene",
    change: "Adresi değiştir",
    errors: errors.tr,

    aboutVersion: "Sürüm",
    aboutMade: "WaterForm bir Fabrikode ürünüdür. Uygulamanın kendisi sunucuda çalışır; bu pencere onu açan kabuktur.",
    aboutServer: "Sunucu",
    aboutServerVersion: "Sunucu sürümü",
    aboutUnset: "ayarlanmadı",
    aboutProduct: "Ürün sayfası ve destek",
    aboutCompany: "Fabrikode",
    aboutMailAddress: "iletisim@fabrikode.com",
    aboutRights: "© Fabrikode. Üretim için mühendislik yazılımı.",
    checking: "Güncellemeler denetleniyor",
    upToDateTitle: "Güncel",
    upToDateBody: "En son sürümü kullanıyorsunuz.",
    availableTitle: (v) => `WaterForm ${v} hazır`,
    availableBody: "Kurulum bir dakika sürer ve uygulama yeniden açılır. Sunucudaki işleriniz etkilenmez.",
    update: "Güncelle",
    later: "Sonra",
    downloading: "İndiriliyor",
    readyTitle: "Kuruldu",
    readyBody: "Yeni sürüm için uygulamayı yeniden başlatın.",
    restart: "Yeniden başlat",
    failedTitle: "Güncellenemedi",
    close: "Kapat",
  },
  en: {
    connecting: "Connecting",
    connectingButton: "Connecting…",
    formTitle: "Server address",
    formBody: "WaterForm runs on the server at this address. If your company has its own server, type its address.",
    fieldLabel: "Address",
    connect: "Connect",
    cancel: "Cancel",
    formNote: "You can change this later.",
    downTitle: "The server did not answer",
    retry: "Try again",
    change: "Change the address",
    errors: errors.en,

    aboutVersion: "Version",
    aboutMade: "WaterForm is a Fabrikode product. The application itself runs on a server; this window is the shell that opens it.",
    aboutServer: "Server",
    aboutServerVersion: "Server version",
    aboutUnset: "not set",
    aboutProduct: "Product page and support",
    aboutCompany: "Fabrikode",
    aboutMailAddress: "contact@fabrikode.com",
    aboutRights: "© Fabrikode. Engineering software for manufacturing.",
    checking: "Checking for updates",
    upToDateTitle: "Up to date",
    upToDateBody: "You are on the latest version.",
    availableTitle: (v) => `WaterForm ${v} is ready`,
    availableBody: "Installing takes about a minute and the application reopens. Your work on the server is untouched.",
    update: "Update",
    later: "Later",
    downloading: "Downloading",
    readyTitle: "Installed",
    readyBody: "Restart the application to use the new version.",
    restart: "Restart",
    failedTitle: "Could not update",
    close: "Close",
  },
  de: {
    connecting: "Verbindung wird hergestellt",
    connectingButton: "Wird verbunden…",
    formTitle: "Serveradresse",
    formBody: "WaterForm läuft auf dem Server unter dieser Adresse. Wenn Ihre Firma einen eigenen Server hat, geben Sie dessen Adresse ein.",
    fieldLabel: "Adresse",
    connect: "Verbinden",
    cancel: "Abbrechen",
    formNote: "Sie können diese Einstellung später ändern.",
    downTitle: "Der Server hat nicht geantwortet",
    retry: "Erneut versuchen",
    change: "Adresse ändern",
    errors: errors.de,

    aboutVersion: "Version",
    aboutMade: "WaterForm ist ein Produkt von Fabrikode. Die Anwendung selbst läuft auf einem Server. Dieses Fenster ist nur der Rahmen, in dem sie sich öffnet.",
    aboutServer: "Server",
    aboutServerVersion: "Serverversion",
    aboutUnset: "nicht eingerichtet",
    aboutProduct: "Produktseite und Hilfe",
    aboutCompany: "Fabrikode",
    // There is no German mailbox; German customers write to the English one.
    aboutMailAddress: "contact@fabrikode.com",
    aboutRights: "© Fabrikode. Ingenieursoftware für die Fertigung.",
    checking: "Suche nach Aktualisierungen",
    upToDateTitle: "Aktuell",
    upToDateBody: "Sie verwenden die neueste Version.",
    availableTitle: (v) => `WaterForm ${v} ist bereit`,
    availableBody: "Die Installation dauert etwa eine Minute, danach öffnet sich die Anwendung wieder. Ihre Arbeit auf dem Server bleibt unberührt.",
    update: "Aktualisieren",
    later: "Später",
    downloading: "Wird heruntergeladen",
    readyTitle: "Installiert",
    readyBody: "Starten Sie die Anwendung neu, um die neue Version zu verwenden.",
    restart: "Neu starten",
    failedTitle: "Aktualisierung fehlgeschlagen",
    close: "Schließen",
  },
};
